# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schedule_tile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='schedule_tile.proto',
  package='alltransit',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x13schedule_tile.proto\x12\nalltransit\"g\n\x0cScheduleTile\x12\x15\n\tpositions\x18\x01 \x03(\x02\x42\x02\x10\x01\x12\x16\n\ntimestamps\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\x18\n\x0cstartIndices\x18\x03 \x03(\rB\x02\x10\x01\x12\x0e\n\x06length\x18\x04 \x01(\r')
)




_SCHEDULETILE = _descriptor.Descriptor(
  name='ScheduleTile',
  full_name='alltransit.ScheduleTile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='positions', full_name='alltransit.ScheduleTile.positions', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='alltransit.ScheduleTile.timestamps', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startIndices', full_name='alltransit.ScheduleTile.startIndices', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='alltransit.ScheduleTile.length', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['ScheduleTile'] = _SCHEDULETILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScheduleTile = _reflection.GeneratedProtocolMessageType('ScheduleTile', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULETILE,
  '__module__' : 'schedule_tile_pb2'
  # @@protoc_insertion_point(class_scope:alltransit.ScheduleTile)
  })
_sym_db.RegisterMessage(ScheduleTile)


_SCHEDULETILE.fields_by_name['positions']._options = None
_SCHEDULETILE.fields_by_name['timestamps']._options = None
_SCHEDULETILE.fields_by_name['startIndices']._options = None
# @@protoc_insertion_point(module_scope)
