'use strict'; // code generated by pbf v3.2.1

// ScheduleTile ========================================

var ScheduleTile = exports.ScheduleTile = {};

ScheduleTile.read = function (pbf, end) {
    return pbf.readFields(ScheduleTile._readField, {positions: [], timestamps: [], startIndices: [], length: 0}, end);
};
ScheduleTile._readField = function (tag, obj, pbf) {
    if (tag === 1) pbf.readPackedFloat(obj.positions);
    else if (tag === 2) pbf.readPackedFloat(obj.timestamps);
    else if (tag === 3) pbf.readPackedVarint(obj.startIndices);
    else if (tag === 4) obj.length = pbf.readVarint();
};
ScheduleTile.write = function (obj, pbf) {
    if (obj.positions) pbf.writePackedFloat(1, obj.positions);
    if (obj.timestamps) pbf.writePackedFloat(2, obj.timestamps);
    if (obj.startIndices) pbf.writePackedVarint(3, obj.startIndices);
    if (obj.length) pbf.writeVarintField(4, obj.length);
};
